/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as IaRouteImport } from './routes/ia'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SorteioTokenRouteImport } from './routes/sorteio.$token'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as PainelIdRouteImport } from './routes/painel.$id'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as ConviteSlugRouteImport } from './routes/convite.$slug'
import { Route as CheckinIdRouteImport } from './routes/checkin.$id'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteioTokenRoute = SorteioTokenRouteImport.update({
  id: '/sorteio/$token',
  path: '/sorteio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIdRoute = PainelIdRouteImport.update({
  id: '/painel/$id',
  path: '/painel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteSlugRoute = ConviteSlugRouteImport.update({
  id: '/convite/$slug',
  path: '/convite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinIdRoute = CheckinIdRouteImport.update({
  id: '/checkin/$id',
  path: '/checkin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ia': typeof IaRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/convite/$slug': typeof ConviteSlugRoute
  '/editor/$id': typeof EditorIdRoute
  '/painel/$id': typeof PainelIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sorteio/$token': typeof SorteioTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ia': typeof IaRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/convite/$slug': typeof ConviteSlugRoute
  '/editor/$id': typeof EditorIdRoute
  '/painel/$id': typeof PainelIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sorteio/$token': typeof SorteioTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ia': typeof IaRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/templates': typeof TemplatesRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/convite/$slug': typeof ConviteSlugRoute
  '/editor/$id': typeof EditorIdRoute
  '/painel/$id': typeof PainelIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sorteio/$token': typeof SorteioTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/ia'
    | '/planos'
    | '/relatorios'
    | '/reset-password'
    | '/templates'
    | '/checkin/$id'
    | '/convite/$slug'
    | '/editor/$id'
    | '/painel/$id'
    | '/rsvp/$token'
    | '/sorteio/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/ia'
    | '/planos'
    | '/relatorios'
    | '/reset-password'
    | '/templates'
    | '/checkin/$id'
    | '/convite/$slug'
    | '/editor/$id'
    | '/painel/$id'
    | '/rsvp/$token'
    | '/sorteio/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/ia'
    | '/planos'
    | '/relatorios'
    | '/reset-password'
    | '/templates'
    | '/checkin/$id'
    | '/convite/$slug'
    | '/editor/$id'
    | '/painel/$id'
    | '/rsvp/$token'
    | '/sorteio/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IaRoute: typeof IaRoute
  PlanosRoute: typeof PlanosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TemplatesRoute: typeof TemplatesRoute
  CheckinIdRoute: typeof CheckinIdRoute
  ConviteSlugRoute: typeof ConviteSlugRoute
  EditorIdRoute: typeof EditorIdRoute
  PainelIdRoute: typeof PainelIdRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
  SorteioTokenRoute: typeof SorteioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteio/$token': {
      id: '/sorteio/$token'
      path: '/sorteio/$token'
      fullPath: '/sorteio/$token'
      preLoaderRoute: typeof SorteioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/$id': {
      id: '/painel/$id'
      path: '/painel/$id'
      fullPath: '/painel/$id'
      preLoaderRoute: typeof PainelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$slug': {
      id: '/convite/$slug'
      path: '/convite/$slug'
      fullPath: '/convite/$slug'
      preLoaderRoute: typeof ConviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$id': {
      id: '/checkin/$id'
      path: '/checkin/$id'
      fullPath: '/checkin/$id'
      preLoaderRoute: typeof CheckinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IaRoute: IaRoute,
  PlanosRoute: PlanosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TemplatesRoute: TemplatesRoute,
  CheckinIdRoute: CheckinIdRoute,
  ConviteSlugRoute: ConviteSlugRoute,
  EditorIdRoute: EditorIdRoute,
  PainelIdRoute: PainelIdRoute,
  RsvpTokenRoute: RsvpTokenRoute,
  SorteioTokenRoute: SorteioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
