/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SorteioTokenRouteImport } from './routes/sorteio.$token'
import { Route as RsvpTokenRouteImport } from './routes/rsvp.$token'
import { Route as PainelIdRouteImport } from './routes/painel.$id'
import { Route as EditorIdRouteImport } from './routes/editor.$id'
import { Route as ConviteSlugRouteImport } from './routes/convite.$slug'
import { Route as CheckinIdRouteImport } from './routes/checkin.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SorteioTokenRoute = SorteioTokenRouteImport.update({
  id: '/sorteio/$token',
  path: '/sorteio/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RsvpTokenRoute = RsvpTokenRouteImport.update({
  id: '/rsvp/$token',
  path: '/rsvp/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIdRoute = PainelIdRouteImport.update({
  id: '/painel/$id',
  path: '/painel/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIdRoute = EditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteSlugRoute = ConviteSlugRouteImport.update({
  id: '/convite/$slug',
  path: '/convite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinIdRoute = CheckinIdRouteImport.update({
  id: '/checkin/$id',
  path: '/checkin/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/convite/$slug': typeof ConviteSlugRoute
  '/editor/$id': typeof EditorIdRoute
  '/painel/$id': typeof PainelIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sorteio/$token': typeof SorteioTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/convite/$slug': typeof ConviteSlugRoute
  '/editor/$id': typeof EditorIdRoute
  '/painel/$id': typeof PainelIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sorteio/$token': typeof SorteioTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/checkin/$id': typeof CheckinIdRoute
  '/convite/$slug': typeof ConviteSlugRoute
  '/editor/$id': typeof EditorIdRoute
  '/painel/$id': typeof PainelIdRoute
  '/rsvp/$token': typeof RsvpTokenRoute
  '/sorteio/$token': typeof SorteioTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/checkin/$id'
    | '/convite/$slug'
    | '/editor/$id'
    | '/painel/$id'
    | '/rsvp/$token'
    | '/sorteio/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/checkin/$id'
    | '/convite/$slug'
    | '/editor/$id'
    | '/painel/$id'
    | '/rsvp/$token'
    | '/sorteio/$token'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/checkin/$id'
    | '/convite/$slug'
    | '/editor/$id'
    | '/painel/$id'
    | '/rsvp/$token'
    | '/sorteio/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CheckinIdRoute: typeof CheckinIdRoute
  ConviteSlugRoute: typeof ConviteSlugRoute
  EditorIdRoute: typeof EditorIdRoute
  PainelIdRoute: typeof PainelIdRoute
  RsvpTokenRoute: typeof RsvpTokenRoute
  SorteioTokenRoute: typeof SorteioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorteio/$token': {
      id: '/sorteio/$token'
      path: '/sorteio/$token'
      fullPath: '/sorteio/$token'
      preLoaderRoute: typeof SorteioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsvp/$token': {
      id: '/rsvp/$token'
      path: '/rsvp/$token'
      fullPath: '/rsvp/$token'
      preLoaderRoute: typeof RsvpTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/$id': {
      id: '/painel/$id'
      path: '/painel/$id'
      fullPath: '/painel/$id'
      preLoaderRoute: typeof PainelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$id': {
      id: '/editor/$id'
      path: '/editor/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof EditorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$slug': {
      id: '/convite/$slug'
      path: '/convite/$slug'
      fullPath: '/convite/$slug'
      preLoaderRoute: typeof ConviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/$id': {
      id: '/checkin/$id'
      path: '/checkin/$id'
      fullPath: '/checkin/$id'
      preLoaderRoute: typeof CheckinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CheckinIdRoute: CheckinIdRoute,
  ConviteSlugRoute: ConviteSlugRoute,
  EditorIdRoute: EditorIdRoute,
  PainelIdRoute: PainelIdRoute,
  RsvpTokenRoute: RsvpTokenRoute,
  SorteioTokenRoute: SorteioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
